### ISSUE TITLE
Fix CI failure on master branch

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-mqlight#30]
master branch now fails on error:

```
1) connection connects with valid settings:
     Uncaught SecurityError: sasl negotiation failed
      at Error (native)
      at _pushChunks (node_modules/mqlight/mqlight.js:1283:27)
      at Socket.dataAvailable (node_modules/mqlight/mqlight.js:1509:32)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:537:20)

  2) messaging "before each" hook: setupSender:
     Uncaught SecurityError: sasl negotiation failed
      at Error (native)
      at _pushChunks (node_modules/mqlight/mqlight.js:1283:27)
      at Socket.dataAvailable (node_modules/mqlight/mqlight.js:1509:32)
      at readableAddChunk (_stream_readable.js:153:18)
      at Socket.Readable.push (_stream_readable.js:111:10)
      at TCP.onread (net.js:537:20)

  3) messaging "after each" hook: teardownReceiver for "creates a message":
     TypeError: Cannot read property 'connected' of undefined
      at Context.teardownReceiver (test/integration/messaging.js:71:17)
```

**Comment by jannyHou** [comment]
Closing in favour of https://github.com/strongloop-internal/scrum-loopback/issues/1258
